### PR TITLE
Pause the core instead of using framebuffer. Fix fastforward.

### PR DESCRIPTION
**Pull request by paulb-nl**

### CODE REVIEW

**Comment by sorgelig** [comment]
FF is still broken. No matter if sync is on or off..

**Comment by SegaSnatcher** [comment]
Yes, FF loses sync with me as well.

**Comment by paulb-nl** [comment]
Which output? On CRT is same behavior as before my changes:

Super Mario Advance gets a bit shaky and gets smaller vertically.
Metroid Zero Mission never had stable fastforward on any build.

On HDMI vsync_adjust=2 I don't think it can stay in sync with fastforward.

**Comment by SegaSnatcher** [comment]
I'm using HDMI output.

**Comment by paulb-nl** [comment]
Ok I see. vsync_adjust=1 loses sync

**Comment by sorgelig** [comment]
Yeah, i'm using vsync_adjust=1 on HDMI

**Comment by sorgelig** [comment]
Key point to not loose the sync is to output the same active area. Amount of blank doesn't matter for vsync_adjust=1.

**Pull request merged**
