### PR TITLE
Fix sprites with 128 height and negative y position

### PR DESCRIPTION
**Pull request by paulb-nl**
The head of the dog in WarioWare Inc was invisible when zoomed in.

### CODE REVIEW

**Comment by RobertPeip** [comment]
Great find. Are you ok with moving the fieldX/Y one cycle earlier into to WAITOAM step, so it doesn't have to be variable for better timing/speed?

**Comment by paulb-nl** [comment]
Well sizeX/Y is not yet available in the WAITOAM step. What do you suggest?

**Comment by RobertPeip** [comment]
We can move it to the cycle before and add it to the case that checks the sprite form.

instead of 
when 0 => sizeX <= 8;  sizeY <= 8; 

we can do once:
doublesize := OAM_data0(OAM_AFFINE) and OAM_data0(OAM_DBLSIZE);

and :
when 0 => sizeX <= 8;  sizeY <= 8;  if (doublesize = '1') then fieldY <= 16; else fieldY <= 8; end if;
for all 12 cases.

The main reason that i fear is the long path:

if (posy > (16#100# - fieldY)) then
   posy := posy - 16#100#;

ty <= ypos_mosaic - posy;

All is run at 100mhz, so having a precalculated fieldY would be nice and relax that path.

**Comment by RobertPeip** [comment]
maybe it's not worth the effort, we can try your change first and if it ever makes problems, we can optimize later.

**Pull request merged**
