### PR TITLE
Apply quirks based on title ID

### PR DESCRIPTION
**Pull request by missionfloyd**

### CODE REVIEW

**Comment by sorgelig** [comment]
using title ID it's better to not compare last letter as it's region specification which should be no matter, so table should be greatly reduced.

**Comment by RobertPeip** [comment]
Yes, really great effort and thanks a lot for doing this step.

As sorgelig mentioned, it would be great if you could bring the games with different regions together, so it should be about the same amount of entries as before, maybe even less.

E.g. instead of 
f(cart_id == {"BPEE"} ) begin gpio_quirk <= 1;
..
if(cart_id == {"BPEI"} ) begin gpio_quirk <= 1;

it should be enough to check only the first 3 bytes for Emerald, so it's only 1 check, not 6.

**Comment by missionfloyd** [comment]
The only problem with doing it that way is that a few NES games are different between regions, so the last byte will still need to be checked for those. I wasn't sure which way would be preferred.

**Comment by sorgelig** [comment]
i think last letter anyway is useless  because there won't be games with different last letter but all same other 3 letters. If game in other region has different ID, then just add compare separately.

**Pull request merged**
